### ISSUE TITLE
Make pk3's into folders instead?

### ISSUE THREAD

**Issue by liback** [nQuake/client-win32#12]
The pk3's seem to cause a lot of confusion, maybe it would be a good idea to stop using them in at least the /qw/ folder. Probably needs quite a bit of testing before doing so though (config execution magic seems to happen depending on structure...)

Noted required changes:
* qw/autoexec.cfg - exec **frogbot**/frogbot.cfg

**Comment by mushis** [comment]
I back this up, for multiple reasons.
a new feature in the latest ezquake is one more reason to do it. `ls` (dir) now has options, and we can change the current aliases `listcharsets `, `listskins `(...) so they use ls instead, listing the actual files in the correspondent folders.
suggestions:
`alias listskins "dir skins * hidedir hideext hidesize; echo use the skin commands (/enemyskin, /teamskin... to set a skin"`
... and similar to charsets, etc

**Comment by mushis** [comment]
**suggested folder structure:**
./qw/crosshairs
./qw/env
./qw/gfx
./qw/maps
./qw/matchinfo
./qw/progs
./qw/skins
./qw/textures

**keep in a pk3?:**
./qw/progs
./qw/lits
./qw/sound

**Comment by mushis** [comment]
I've done this
