### ISSUE TITLE
ezQuake needs updating

### ISSUE THREAD

**Issue by liback** [nQuake/client-win32#28]
People who download nQuake experience this problem:
https://www.quakeworld.nu/news/1108/ezquake-max-neighbours-count-reache

ezQuake version in nQuake needs to be updated to this version:
https://github.com/ezQuake/ezquake-source/releases/tag/3.2.1

**Comment by eb** [comment]
It has been updated in the meantime... also updated today to 3.2.2. I'll try to keep up with new releases from now on.
