### ISSUE TITLE
Some variables not saved on quit

### ISSUE THREAD

**Issue by liback** [nQuake/client-win32#8]
Some variables don't seem to be saved on quit.

Steps to reproduce:
* cfg_save_onquit 1
* gl_no24bits 1
* vid_restart (this is required in the working scenario for this particular cvar)
* quit
* start ezQuake
* gl_no24bits is now back at 0

May be because this particular variable requires a vid_restart?

**Comment by liback** [comment]
Same when testing with vid_fullscreen 0 that also requires a vid_restart.

**Comment by liback** [comment]
The autoexec is the culprit, it seems to take ezQuake default values before execing config.cfg and the real values are only set as "latched" values for parameters requiring a restart.

**Comment by niclaslindstedt** [comment]
Well that's not good

**Comment by liback** [comment]
A weird solution to a weird problem; it seems to be the wait commands causing the latched values for commands requiring a restart:
* Remove wait from _startup_message in autoexec.cfg
* Add wait to end of default.cfg

**Comment by liback** [comment]
I deployed the changes above. Only tiny glitch that I've seen is that one can now see the original ezQuake message for a tiny fraction of a second before the "console menu" is printed. I think it's an ok tradeoff to make config values behave ok.
